<?php

enum EnvName: string
{
    case FLUX_ECO_HTTP_SERVER_SIDECAR_PORT = 'FLUX_ECO_HTTP_SERVER_SIDECAR_PORT';
    case FLUX_ECO_HTTP_SERVER_SIDECAR_WORKER_NUM = 'FLUX_ECO_HTTP_SERVER_SIDECAR_WORKER_NUM';
    case FLUX_ECO_HTTP_SERVER_SIDECAR_TASK_WORKER_NUM = 'FLUX_ECO_HTTP_SERVER_SIDECAR_TASK_WORKER_NUM';
    case FLUX_ECO_HTTP_SERVER_SIDECAR_BACKLOG = 'FLUX_ECO_HTTP_SERVER_SIDECAR_BACKLOG';
    case FLUX_ECO_HTTP_SERVER_SIDECAR_AUTOLOAD_FILE_PATH = 'FLUX_ECO_HTTP_SERVER_SIDECAR_AUTOLOAD_FILE_PATH';
    case FLUX_ECO_HTTP_SERVER_SIDECAR_HTTP_API_FQCN = 'FLUX_ECO_HTTP_SERVER_SIDECAR_HTTP_API_FQCN';
    case FLUX_ECO_HTTP_SERVER_SIDECAR_LOG_FILE_PATH_NAME = 'FLUX_ECO_HTTP_SERVER_SIDECAR_LOG_FILE_PATH_NAME';

    public function toConfigValue() : string|int
    {
        return getenv($this->value);
    }
}